//! Frozen pre-spec-34 (schema v1) vault wire-format types.
//!
//! `NodeRecordV1` describes a bincode encoding that already exists in the
//! world (every `.pidag/pidag.redb` vault written before spec-34) and can
//! never change. It exists **only** to be decoded once, during the v1 -> v2
//! migration in `redb_store::open` (spec-36).
//!
//! **Do not derive this from, alias it to, or refactor it alongside** the
//! live type (`store::NodeRecord`). That is exactly how the original defect
//! happened: spec-34 changed `NodeRecord` and never gave the old shape
//! anywhere to live, so bincode -- which is not self-describing -- silently
//! misread every old record. See spec-36 and `docs/FINDINGS.md` ("The
//! compatibility guard was regenerated by the change it was guarding").
//!
//! Only tables whose on-disk format actually changed get a mirror type here.
//! spec-36 originally added `EventV1` on the premise that spec-34 had also
//! changed a field inside the `Event` enum; that premise was checked against
//! the committed fixture and found false -- no `Event` variant has ever
//! carried a `state` field, so the events wire format never changed. `EventV1`
//! was withdrawn (spec-36 V6 withdrawal) rather than kept as a speculative,
//! permanently-maintained copy of a live type for no behavioural benefit.

use crate::scheduler::NodeStatus;
use crate::store::NodeRecord;
use serde::{Deserialize, Serialize};

/// v1 shape of `store::NodeRecord`. Identical except `state`, which was a
/// plain `String` before spec-34 introduced the `NodeStatus` enum.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeRecordV1 {
    pub node_id: String,
    pub state: String,
    pub model: Option<String>,
    pub attempt: usize,
    pub timestamp: String,
}

impl NodeRecordV1 {
    /// Convert to the current `NodeRecord`. This is the call site spec-36
    /// exists to give `NodeStatus::parse` -- spec-34 wrote that function
    /// "for deserialization from legacy data" but nothing ever called it.
    ///
    /// Returns `Err` naming the node and the unrecognised status string if
    /// `state` is not one of the five known values (spec-36 V7). Callers
    /// must **not** substitute a default: fabricating `Pending` for a node
    /// that actually failed would produce a wrong, silently-resumable state.
    pub fn migrate(self) -> Result<NodeRecord, String> {
        let state = NodeStatus::parse(&self.state).map_err(|_| {
            format!(
                "unrecognised legacy status {:?} for node {:?}",
                self.state, self.node_id
            )
        })?;
        Ok(NodeRecord {
            node_id: self.node_id,
            state,
            model: self.model,
            attempt: self.attempt,
            timestamp: self.timestamp,
        })
    }
}
