//! Frozen pre-spec-34 (schema v1) vault wire-format types.
//!
//! `NodeRecordV1` and `EventV1` describe a bincode encoding that already
//! exists in the world (every `.pidag/pidag.redb` vault written before
//! spec-34) and can never change. They exist **only** to be decoded once,
//! during the v1 -> v2 migration in `redb_store::open` (spec-36).
//!
//! **Do not derive these from, alias them to, or refactor them alongside**
//! the live types (`store::NodeRecord`, `core::event::Event`). That is
//! exactly how the original defect happened: spec-34 changed `NodeRecord`
//! and never gave the old shape anywhere to live, so bincode -- which is not
//! self-describing -- silently misread every old record. See spec-36 and
//! `docs/FINDINGS.md` ("The compatibility guard was regenerated by the
//! change it was guarding").
//!
//! Note on `EventV1`: nothing in this codebase's current `Event` enum
//! carries a `state` field (checked directly against the committed
//! `tests/fixtures/legacy_vault/legacy.redb` fixture -- every event in it
//! decodes cleanly against the *current* `Event` type). `EventV1` is kept as
//! an independent frozen mirror of `Event` anyway, per spec-36's decision
//! that these types must not be tied to the live ones; the migration copies
//! `events` through it rather than assuming the current `Event` shape will
//! always stay wire-compatible with whatever is on disk.

use crate::core::event::Event;
use crate::scheduler::NodeStatus;
use crate::store::NodeRecord;
use serde::{Deserialize, Serialize};

/// v1 shape of `store::NodeRecord`. Identical except `state`, which was a
/// plain `String` before spec-34 introduced the `NodeStatus` enum.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NodeRecordV1 {
    pub node_id: String,
    pub state: String,
    pub model: Option<String>,
    pub attempt: usize,
    pub timestamp: String,
}

impl NodeRecordV1 {
    /// Convert to the current `NodeRecord`. This is the call site spec-36
    /// exists to give `NodeStatus::parse` -- spec-34 wrote that function
    /// "for deserialization from legacy data" but nothing ever called it.
    ///
    /// Returns `Err` naming the node and the unrecognised status string if
    /// `state` is not one of the five known values (spec-36 V7). Callers
    /// must **not** substitute a default: fabricating `Pending` for a node
    /// that actually failed would produce a wrong, silently-resumable state.
    pub fn migrate(self) -> Result<NodeRecord, String> {
        let state = NodeStatus::parse(&self.state).map_err(|_| {
            format!(
                "unrecognised legacy status {:?} for node {:?}",
                self.state, self.node_id
            )
        })?;
        Ok(NodeRecord {
            node_id: self.node_id,
            state,
            model: self.model,
            attempt: self.attempt,
            timestamp: self.timestamp,
        })
    }
}

/// v1 shape of `core::event::Event`. See the module-level note: no variant
/// here actually differs from the current `Event` in field types (none
/// carried a raw status string), so `migrate` is a structural copy rather
/// than a parse. The type is still kept separate and frozen, not aliased to
/// `Event`, so a future change to `Event` cannot silently change what this
/// migration reads off old disks.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum EventV1 {
    DagSubmitted,
    DagDone {
        successful_nodes: usize,
        failed_nodes: usize,
    },
    NodeDispatched {
        node_id: String,
        model: String,
        attempt: usize,
    },
    NodeDone {
        node_id: String,
        model: String,
        output: String,
    },
    NodeFailed {
        node_id: String,
        error: String,
    },
    NodeBlocked {
        node_id: String,
    },
    NodeRetry {
        node_id: String,
        reason: String,
    },
    ProviderFallback {
        node_id: String,
        from_model: String,
        to_model: String,
    },
    NodeSkipped {
        node_id: String,
        reason: String,
    },
    NodeVerifyFailed {
        node_id: String,
        worker_claim: String,
        verify_output: String,
    },
}

impl EventV1 {
    /// Convert to the current `Event`. Infallible: every field here is a
    /// primitive (`String`/`usize`) whose bincode encoding does not depend
    /// on the `NodeStatus` change.
    pub fn migrate(self) -> Event {
        match self {
            EventV1::DagSubmitted => Event::DagSubmitted,
            EventV1::DagDone {
                successful_nodes,
                failed_nodes,
            } => Event::DagDone {
                successful_nodes,
                failed_nodes,
            },
            EventV1::NodeDispatched {
                node_id,
                model,
                attempt,
            } => Event::NodeDispatched {
                node_id,
                model,
                attempt,
            },
            EventV1::NodeDone {
                node_id,
                model,
                output,
            } => Event::NodeDone {
                node_id,
                model,
                output,
            },
            EventV1::NodeFailed { node_id, error } => Event::NodeFailed { node_id, error },
            EventV1::NodeBlocked { node_id } => Event::NodeBlocked { node_id },
            EventV1::NodeRetry { node_id, reason } => Event::NodeRetry { node_id, reason },
            EventV1::ProviderFallback {
                node_id,
                from_model,
                to_model,
            } => Event::ProviderFallback {
                node_id,
                from_model,
                to_model,
            },
            EventV1::NodeSkipped { node_id, reason } => Event::NodeSkipped { node_id, reason },
            EventV1::NodeVerifyFailed {
                node_id,
                worker_claim,
                verify_output,
            } => Event::NodeVerifyFailed {
                node_id,
                worker_claim,
                verify_output,
            },
        }
    }
}
